POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Juanito Gomez",
    "number":"12245-45677"
}


###################

GET http://localhost:3001/api/persons


###################

PUT http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"nn",
    "number":"12245"
}